"""Phase 5A: grievances with status timeline and AI triage fields

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-27 08:52:20.651106
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Created once up front: grievance_status is shared by two tables.
grievance_category = postgresql.ENUM('delivery', 'wrong_or_fake_item', 'damaged', 'refund', 'payment', 'seller', 'account', 'other', name='grievance_category', create_type=False)
grievance_priority = postgresql.ENUM('low', 'medium', 'high', 'urgent', name='grievance_priority', create_type=False)
grievance_status = postgresql.ENUM('open', 'in_progress', 'ai_resolved', 'resolved', name='grievance_status', create_type=False)
grievance_actor = postgresql.ENUM('customer', 'ai', 'admin', name='grievance_actor', create_type=False)
ENUMS = (grievance_category, grievance_priority, grievance_status, grievance_actor)


def upgrade() -> None:
    for enum_type in ENUMS:
        enum_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('category', grievance_category, nullable=False),
    sa.Column('priority', grievance_priority, nullable=False),
    sa.Column('status', grievance_status, nullable=False),
    sa.Column('ai_summary', sa.String(length=300), nullable=True),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('triaged_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_user_id'), 'grievances', ['user_id'], unique=False)
    op.create_table('grievance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('status', grievance_status, nullable=False),
    sa.Column('actor', grievance_actor, nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_events_grievance_id'), 'grievance_events', ['grievance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_events_grievance_id'), table_name='grievance_events')
    op.drop_table('grievance_events')
    op.drop_index(op.f('ix_grievances_user_id'), table_name='grievances')
    op.drop_table('grievances')
    for enum_type in reversed(ENUMS):
        enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
