"""Sizes: per-size stock (product_variants), size charts, fit feedback, size exchanges

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 08:23:54.119403
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


review_fit = postgresql.ENUM('runs_small', 'true_to_size', 'runs_large', name='review_fit', create_type=False)


def upgrade() -> None:
    # add_column doesn't create enum types on PostgreSQL, so create it explicitly.
    review_fit.create(op.get_bind(), checkfirst=True)
    # Autogenerate can't see new values of an existing enum.
    op.execute("ALTER TYPE return_reason ADD VALUE IF NOT EXISTS 'wrong_size'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('stock >= 0', name='ck_product_variants_stock_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size', name='uq_product_variants_product_size')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.add_column('cart_items', sa.Column('size', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('uq_cart_items_user_product'), 'cart_items', type_='unique')
    op.create_unique_constraint('uq_cart_items_user_product_size', 'cart_items', ['user_id', 'product_id', 'size'], postgresql_nulls_not_distinct=True)
    op.add_column('order_items', sa.Column('size', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('size_chart', sa.JSON(), nullable=True))
    op.add_column('return_requests', sa.Column('exchange_size', sa.String(length=20), nullable=True))
    op.add_column('reviews', sa.Column('fit', review_fit, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'fit')
    op.drop_column('return_requests', 'exchange_size')
    op.drop_column('products', 'size_chart')
    op.drop_column('order_items', 'size')
    op.drop_constraint('uq_cart_items_user_product_size', 'cart_items', type_='unique')
    op.create_unique_constraint(op.f('uq_cart_items_user_product'), 'cart_items', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cart_items', 'size')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    review_fit.drop(op.get_bind(), checkfirst=True)
    # Note: PostgreSQL can't remove the 'wrong_size' value from return_reason; it stays (unused).
    # ### end Alembic commands ###
