"""3D models: optional glTF model link + attribution per product (3D viewer and AR)

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-29 09:35:56.392084
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('model_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('model_credit', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'model_credit')
    op.drop_column('products', 'model_url')
    # ### end Alembic commands ###
